apiVersion: v1
# kind indicates the type of object we want to make.
# A pod is used to run a container
kind: Pod 
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-worker
      ports:
        - containerPort: 3000